### ISSUE TITLE
How to: sort by something other than category? 

### ISSUE THREAD

**Issue by cramatt** [jsdoc2md/dmd-plugin-example#1]
I'm attempting to make a plugin for angular and I'd like to sort by `@ngdoc`. Currently I see sorting by category is supported. Any suggestions? Thanks!

**Comment by 75lb** [comment]
hi.. for now (until i put a sort option back in) you can obtain the template data yourself (via [`getTemplateData()`](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#module_jsdoc-to-markdown--JsdocToMarkdown+getTemplateData), sort it as desired then pass it into the `options.data` option of [`.render()`](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdrenderoptions--promise).

Closing as I already have a ticket regarding sorting.

**Comment by cramatt** [comment]
Thanks for the prompt reply!
